---
title: "Final Project"
author: "Truc, Mary, Lik, Mengna "
date: "12/1/2020"
header-includes:
   - \usepackage{enumerate,graphicx}
geometry: margin=0.5in 
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
set.seed(1)
library(ggplot2)
library(knitr)
library(magrittr) 
library(dplyr)
library(tidyverse)
library(ggcorrplot)
library(rpart)
library(rpart.plot)
library(tree)
library(ISLR)
library(caret)
library(randomForest)
library(gbm)
library(lda)
library(ROCR)
library(corrplot)
library(MASS)
library(caTools)
library(rsample)
#######Set up and Data Wrangling########

setwd("/Users/trucle/Desktop/STA\ 138/Bank/bank-additional")
# for this project we will be using the bank-additional-full.csv to do our analysis on.

bank_additional_full <- read.csv("bank-additional-full.csv", sep=";", stringsAsFactors = F, header = T) 
# this allows for the data to be separated rather than being mushed together.

# to see how many rows have missing data
sum(!complete.cases(bank_additional_full))

sapply(bank_additional_full, function(x) sum(is.na(x))) # this shows that there is no missing values within the dataset for any categories


write.csv(bank_additional_full, "cleaned_bank_additional_full.csv") 
# this write the clean data into a separate csv that we can use to work with


bank <- read.csv("cleaned_bank_additional_full.csv")[-1] 
# -1 to get rid of them counting the # of rows 

# we transformed all of the quantitative values into numeric class for easier manipulation later on. 
bank$age <- as.numeric(bank$age)
bank$duration <- as.numeric(bank$duration)
bank$campaign <- as.numeric(bank$campaign)
bank$pdays <- as.numeric(bank$pdays)
bank$previous <- as.numeric(bank$previous)
bank$emp.var.rate <- as.numeric(bank$emp.var.rate)
bank$cons.price.idx <- as.numeric(bank$cons.price.idx)
bank$cons.conf.idx <- as.numeric(bank$cons.conf.idx)
bank$nr.employed <- as.numeric(bank$nr.employed)

# this checks if there are any missing data within each categories and push them into a category of there own. 
# this shows the counts for each groups within each categories, run summary(bank) to see the result
bank$job = fct_explicit_na(bank$job, "missing")
bank$marital = fct_explicit_na(bank$marital, "missing")
bank$education = fct_explicit_na(bank$education, "missing")
bank$default = fct_explicit_na(bank$default, "missing")
bank$loan = fct_explicit_na(bank$loan, "missing")
bank$contact = fct_explicit_na(bank$contact, "missing")
bank$poutcome = fct_explicit_na(bank$poutcome, "missing")
bank$day_of_week = fct_explicit_na(bank$day_of_week, "missing")
bank$housing = fct_explicit_na(bank$housing, "missing")
bank$month = fct_explicit_na(bank$month, "missing")

bank$y =ifelse(bank$y =='yes',1,0) # transforming 'yes' category into a binary 1=yes 0=no
```

```{r, echo=FALSE, eval=TRUE}
##### Data Exploration ######
summary(bank) # summary of each categories 

str(bank) # show the content of each categories 

prop.table(table(bank$y)) 
# the dataset predicted outcome (y) is skewed towards 'no' with over 88%

# checking the sixe of the dataset
bank_row = nrow(bank)
bank_col = ncol(bank)

# observation of the dataset
head(bank)

bank %>% 
  dplyr::select(age, duration, campaign, emp.var.rate, cons.price.idx, cons.conf.idx, euribor3m, nr.employed,y) %>% 
  cor() %>% 
  corrplot(method = "pie",
           type = "upper",
           tl.cex = 0.8,
           tl.srt = 45,
           tl.col = "black",
           title = "Correlation Matrix for all Numerical Variables ")

# Scatter Plot Matrix
bank_matrix_factor1 <- bank %>% dplyr::select(job, marital, education, default, housing)
pairs(bank_matrix_factor1)

bank_matrix_factor2 <-bank %>% dplyr::select(loan,
                                      contact,month,day_of_week,poutcome)
pairs(bank_matrix_factor2)


```

```{r, echo=FALSE, eval=TRUE}
##### Category: Age
summary(bank$age)
gg <- ggplot(bank)

# histogram plot for the distribution of age
his_age = gg + geom_histogram(aes(x=age), color = "black", fill ="white", binwidth = 1) + 
  ggtitle("Age Distribution")+
  xlab("Age") + ylab("Counts")+
  geom_vline(aes(xintercept=mean(age), color="red"))+
  theme(legend.position = "none")

# Box plot for Age
bp_age = gg+ geom_boxplot(aes(x="", y=age),outlier.colour = "red")+
  ggtitle("Age Boxplot")+ ylab("Age")
# made outliers data points red

mean_age <- bank_additional_full %>% group_by(y) %>% summarize(grp.mean=mean(age))

his_age_sub = ggplot (bank_additional_full, aes(x=age)) + 
  geom_histogram(color = "black", fill = "green", binwidth = 1) +
  ggtitle('Subscription of Term Deposit by Age') + ylab('Count') + xlab('Age') +
  facet_grid(cols=vars(y))+
  scale_x_continuous(breaks = seq(0,100,5)) +
  geom_vline(data=mean_age, aes(xintercept=grp.mean), color="red", linetype="dashed") + geom_vline(data=bank_additional_full, aes(xintercept=mean(age)), color="black")
# this output two histograms for comparison, left histogram is for Age Distribution and the right histogram is for Subscription by Age. The black line shows the mean of the age superimposed onto the histograms and the dashed red line shows the mean of the age that subscriped onto the term deposit. 

bank_additional_full %>% 
  group_by(age) %>% 
  summarize(age.cnt = n(), pct.con.yes = mean(y=="yes")*100) %>% 
  arrange(desc(age.cnt)) %>% 
  head() 

```

```{r, echo=FALSE, eval=TRUE}
# Category: Education
summary(bank$education)

#Bar graph for education 
gg_edu=ggplot(bank, aes(x = education, fill=education))+geom_bar()+ggtitle("Distribution of Education Levels")

# Subscription by Education
edu_sub = ggplot(data = bank_additional_full, aes(x=education, fill=y)) +
         geom_bar() +
         ggtitle("Term Deposit Subscription based on Education Level") +
         xlab(" Education Level") +
         guides(fill=guide_legend(title="Subscription of Term Deposit"))
# need to use the bank_additional_full dataset to get the two layers bar graphs.

# Percentage of Yes within each group based on their education level 
bank_additional_full %>% 
  group_by(education) %>% 
  summarize(pct.yes = mean(y=="yes")*100) %>% 
  arrange(desc(pct.yes))

```

```{r, echo=FALSE, eval=TRUE}
# Category: Job
summary(bank$job)

# bar graph for job
gg_job = ggplot(bank, aes(x = job, fill=job))+geom_bar()+ggtitle("Distribution of Jobs") 

# subscription by job title 
job_sub = ggplot(data = bank_additional_full, aes(x=job, fill=y)) +
         geom_bar() +
         ggtitle("Term Deposit Subscription based on Job Position") +
         xlab(" Job Position") +
         guides(fill=guide_legend(title="Subscription of Term Deposit"))

# Percentage of Yes in each group based on their job title
bank_additional_full %>% 
  group_by(job) %>% 
  summarize(pct.yes = mean(y=="yes")*100) %>% 
  arrange(desc(pct.yes))
```
```{r, echo=FALSE, eval=TRUE}
# Category: Martial Statues  

# bar chart for martial status
gg_martial = ggplot(bank, aes(x = marital, fill=marital)) + geom_bar() + 
  ggtitle("Distribution of Martial Status") + xlab("Martial Status")

# Subscription by marital status 
marital_sub = ggplot(bank_additional_full, aes(x = marital, fill=y)) + geom_bar() + 
  ggtitle("Distribution of Martial Status by subscription") + xlab("Martial Status")

# Percentage of Yes in each group based on their Marital status 

bank_additional_full %>% 
  group_by(marital) %>% 
  summarize(pct.yes = mean(y=="yes")*100) %>% 
  arrange(desc(pct.yes))

```
```{r, echo=FALSE, eval=TRUE}
# Consumer Price Index Distribution Graphs
summary(bank$cons.price.idx)
# Using GGplot, I constructed a bar graph to show the distribution of the consumer price index
bar_price.idx=ggplot(bank, aes(x = cons.price.idx, fill=cons.price.idx)) + geom_bar()+
  geom_vline(aes(xintercept=mean(cons.price.idx)),color="red")+ggtitle("Consumer Price Index with Red Mean Line")

# Box plot for Consumer Price Index
bp_cpi = gg+ geom_boxplot(aes(x="", y=cons.price.idx),outlier.colour = "red")+
  ggtitle("Consumer Price Index Boxplot")+ ylab("Consumer Price Index")

# Subscription by Consumer Price Index

bar_cpi_sub = ggplot(bank_additional_full, aes(x = cons.price.idx, fill=y)) + geom_bar() + 
  ggtitle("Term Deposit of Subscription by Consumer Price Index") + xlab("Consumer Price Index")

his_cpi_sub =  ggplot(bank_additional_full, aes(x = cons.price.idx, fill=y)) + geom_histogram(color="black", fill="red", binwidth = 0.05) +facet_grid(cols=vars(y))

bank_additional_full %>% 
  group_by(cons.price.idx) %>% 
  summarize(cpi.cnt = n(), pct.con.yes = mean(y=="yes")*100) %>% 
  arrange(desc(cpi.cnt)) %>% 
  head() 

```


```{r, echo=FALSE, eval=TRUE}

# Category: Consumer Confidence Index Graphs 
summary(bank$cons.conf.idx)

bar_conf.idx=ggplot(bank, aes(x = cons.conf.idx, fill=cons.conf.idx)) + geom_bar()+
  ggtitle("Consumer Confidence Index Bar Graph")

# Box plot for Consumer Confidence Index
bp_cci = gg+ geom_boxplot(aes(x="", y=cons.conf.idx),outlier.colour = "red")+
  ggtitle("Consumer Confidence Index Boxplot")+ ylab("Consumer Confidence Index")

# Subscription by Consumer Price Index

bar_cci_sub = ggplot(bank_additional_full, aes(x = cons.conf.idx, fill=y)) + geom_bar() + 
  ggtitle("Term Deposit of Subscription by Consumer Confidence Index") + xlab("Consumer Confidence Index")

his_cci_sub = ggplot(bank_additional_full, aes(x=cons.conf.idx, fill=y)) +
  geom_histogram(color="black", fill="red", binwidth = 1)+
  facet_grid(cols=vars(y))+ggtitle("Term Deposit of Subscription by Consumer Confidence Index") +xlab("Consumer Confidence Index")

bank_additional_full %>% 
  group_by(cons.conf.idx) %>% 
  summarize(cci.cnt = n(), pct.con.yes = mean(y=="yes")*100) %>% 
  arrange(desc(cci.cnt)) %>% 
  head() 
                                                                      
```

```{r, echo=FALSE, eval=TRUE}
# Category: Campaign
summary(bank$campaign)

bar_campaign=ggplot(bank, aes(x = campaign, fill=campaign)) + geom_bar()+
  ggtitle("Campaign")

# Box plot for Campaign
bp_campaign = gg+ geom_boxplot(aes(x="", y=campaign),outlier.colour = "red")+
  ggtitle("Campaign")+ ylab("Campaign")

bar_campaign_sub = ggplot(bank_additional_full, aes(x = campaign, fill=y)) + geom_bar() + 
  ggtitle("Term Deposit of Subscription by Campaign") + xlab("Campaign")+xlim(c(min=0, max=30))

his_campaign_sub = ggplot(bank_additional_full, aes(x = campaign, fill=y)) + geom_histogram() + 
  ggtitle("Term Deposit of Subscription by Campaign") + xlab("Campaign")+xlim(c(min=0, max=30))

bank_additional_full %>% 
  group_by(campaign) %>% 
  summarize(contact.cnt = n(), pct.con.yes = mean(y=="yes")*100) %>% 
  arrange(desc(contact.cnt)) %>% 
  head() 
```

```{r, echo=FALSE, eval=TRUE}
# Category : Duration

summary(bank$duration)

bar_duration=ggplot(bank, aes(x = duration, fill=duration)) + geom_bar(fill="blue")+
  ggtitle("Duration Distribution")

mean_duration <- bank_additional_full %>% group_by(y) %>% summarize(grp.mean=mean(duration))

his_dur_sub = ggplot(bank_additional_full, aes(x = duration, fill=y)) + geom_histogram(binwidth = 2) +
  facet_grid(cols=vars(y))+
  ggtitle("Term Deposit of Subscription by Duration") + xlab("Duration")+coord_cartesian(xlim = c(0,2000), ylim = c(0,1000))+geom_vline(data=mean_duration, aes(xintercept = grp.mean), color="red")

```

```{r, echo=FALSE, eval=TRUE}
# Employment Variation Rate
summary(bank$emp.var.rate)

his_evr = ggplot(bank, aes(x = emp.var.rate, fill=emp.var.rate)) + geom_histogram(fill="blue")+
  ggtitle("Employment Variation Rate")

mean_evr <- bank_additional_full %>% group_by(y) %>% summarize(grp.mean=mean(emp.var.rate))

his_evr_sub = ggplot(bank_additional_full, aes(x = emp.var.rate, fill=y)) + geom_histogram(binwidth = 2) +facet_grid(cols=vars(y))+ggtitle("Term Deposit of Subscription by Employment Variation Rate") + xlab("Employment Variation Rate")+geom_vline(data=mean_evr, aes(xintercept = grp.mean), color="red")

bank_additional_full %>% 
  group_by(emp.var.rate) %>% 
  summarize(contact.cnt = n(), pct.con.yes = mean(y=="yes")*100) %>% 
  arrange(desc(contact.cnt)) %>% 
  head() 
```

```{r, echo=FALSE, eval=TRUE}
#### Comparison of Variables

```

```{r, echo=FALSE, eval=TRUE}
#Split the Training / Testing data 
split = sample.split(bank$y,SplitRatio = 0.70)
train = subset(bank, split == TRUE)
test = subset(bank, split == FALSE)

```

```{r, echo=FALSE, eval=TRUE}
# Model 1: Decision Tree with training set
tree_model <-rpart(y ~ .,
                   data=train,
                   method ="class")
rpart.plot(tree_model,
           main="Decision Tree",
           type=2,
           extra = 104,
           fallen.leaves = TRUE)
# type= 2 : draw the split labels below the node labels
# extra = 104 : class model with a response having more than two levels

#Evaluating the Decision Tree Model

#prediction model
pred<-predict(tree_model,test,type = "class")
#confusion matrix
confusionMatrix(as.factor(test$y),as.factor(pred))

# calculate ROC curve
pred.DT = predict(tree_model, newdata = test, type = 'prob')
rocr.pred = prediction(predictions=pred.DT[,2], labels = test$y)
rocr.perf = performance(rocr.pred, measure = "tpr", x.measure = "fpr")
rocr.auc = as.numeric(performance(rocr.pred, "auc")@y.values)

# print ROC AUC
rocr.auc

#plot ROC curve
roc_curve<-{plot(rocr.perf,
     lwd = 3, colorize = TRUE,
     print.cutoffs.at = seq(0, 1, by = 0.1),
     text.adj = c(-0.2, 1.7),
     main = 'ROC Curve')
mtext(paste('Decision Tree - auc : ', round(rocr.auc, 5)))
abline(0, 1, col = "red", lty = 1)}


```


```{r, echo=FALSE, eval=TRUE}

# Model 2: Logistic Regression
set.seed(123)

table(train$y)

bank_glm <- glm(formula = y ~ age+ job + marital + education + default + housing + 
    loan + contact + month + duration+ day_of_week + campaign + pdays + 
    previous + poutcome + emp.var.rate + cons.price.idx + cons.conf.idx + 
    euribor3m + nr.employed, family = "binomial", data = train)

summary(bank_glm)

bank_glm_pred <- predict(bank_glm, test, type = "response")

bank_glm_pred_label <- as.factor(ifelse(bank_glm_pred>.7, "1", "0"))

confusionMatrix(factor(bank_glm_pred), factor(test$y), positive = "1")

bank_glm_roc <- prediction(bank_glm_pred, test$y)
rocr.perf_glm=performance(bank_glm_roc, "tpr", "fpr")
bank_glm_auc <- performance(bank_glm_roc, "auc")
auc_glm<-bank_glm_auc@y.values[[1]]


# print ROC AUC
auc_glm

#plot ROC curve
roc_curve<-{plot(rocr.perf_glm,
     lwd = 3, colorize = TRUE,
     print.cutoffs.at = seq(0, 1, by = 0.1),
     text.adj = c(-0.2, 1.7),
     main = 'ROC Curve')
mtext(paste('Decision Tree - auc : ', round(auc_glm, 5)))
abline(0, 1, col = "red", lty = 1)}
```

```{r, echo=FALSE, eval=TRUE}
# Model 3: K-Nearest Neighbor
# have to make the y into a factor in order to run the knn code
train$y <- as.factor(train$y)
train$y <- as.factor(train$y)

model.KNN <- kknn( y ~ age+ job + marital + education + default + housing + 
    loan + contact + month + duration+ day_of_week + campaign + pdays + 
    previous + poutcome + emp.var.rate + cons.price.idx + cons.conf.idx + 
    euribor3m + nr.employed, train, test, k=5, distance = 2)
summary(model.KNN)


bank_knn_pred <- predict(model.KNN, test, type="raw")
bank_knn_pred_label <- table(bank_knn_pred, test$y)
confusionMatrix(bank_knn_pred_label, positive = "yes")


pb <- predict(model.KNN, na.roughfix(test), type="prob")
pb <- as.data.frame(pb)
pred.KNN <- data.frame(test$y, pb$yes)

labels <- as.factor(ifelse(pred.KNN$test.y=="yes", 1, 0))
predictions <- pred.KNN$pb.yes
auc_knn<-auc(roc(predictions, labels), min = 0, max = 1)


{plot(roc(predictions, labels), col="blue",
      lwd=3,
     print.cutoffs.at = seq(0, 1, by = 0.1),
      main= "ROC Curve")
  mtext(paste('K-Nearest Neighbors - auc : ', round(auc_knn, 5)))
  abline(0, 1, col = "red", lty = 1)}
      

```

```{r, ref.label=knitr::all_labels(),echo=TRUE,eval=FALSE}
# this is the code appendix 
```
