---
title: "Final Project"
author: "Truc, Mary, Lik, Mengna "
date: "12/1/2020"
header-includes:
   - \usepackage{enumerate,graphicx}
geometry: margin=0.5in 
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
library(ggplot2)
library(knitr)


# This is the set up and data wrangling portion
setwd("/Users/trucle/Desktop/STA\ 138/Bank/bank-additional")
# for this project we will be using the bank-additional-full.csv to do our analysis on.

bank_additional_full <- read.csv("bank-additional-full.csv", sep=";", stringsAsFactors = F, header = T) 
# this allows for the data to be separated rather than being mushed together.

write.csv(bank_additional_full, "cleaned_bank_additional_full.csv") 
# this write the clean data into a separate csv that we can use to work with

any(is.na(bank_additional_full))
# this to see if the data has been cleaned of all missing data.

bank <- read.csv("cleaned_bank_additional_full.csv")[-1] 
# -1 to get rid of them counting the # of rows 

# we transformed all of the quantitative values into numeric class for easier manipulation later on. 
bank$age <- as.numeric(bank$age)
bank$duration <- as.numeric(bank$duration)
bank$campaign <- as.numeric(bank$campaign)
bank$pdays <- as.numeric(bank$pdays)
bank$previous <- as.numeric(bank$previous)
bank$emp.var.rate <- as.numeric(bank$emp.var.rate)
bank$cons.price.idx <- as.numeric(bank$cons.price.idx)
bank$cons.conf.idx <- as.numeric(bank$cons.conf.idx)
bank$nr.employed <- as.numeric(bank$nr.employed)

sapply(bank, function(x) sum(is.na(x))) # this shows that there is no missing values within the dataset for any categories


bank$y =ifelse(bank$y =="yes",1,0) # transforming 'yes' category into a binary 1=yes 0=no
```

```{r, echo = FALSE,eval = TRUE}
# Data exploration 
summary(bank)

prop.table(table(bank$y)) 
#Observe that the dataset predicted outcome (y) is skewed towards ‘no’ with over 88%.

gg <- ggplot(bank)

#Age Distribution Graphs 
summary(bank$age)
# Using GGplot, I constructed a histogram to show the age distribution along with the red line to indicate the mean  
his_age = gg + geom_histogram(aes(x=age), color="black", fill="white", binwidth = 1)+
  ggtitle("Age Distribbution")+xlab("Age")+ylab("Counts")+
  geom_vline(aes(xintercept = mean(age), color="red"))+
  theme(legend.position = "none")

# Box plot for Age 
bp_age = gg + geom_boxplot(aes(x="",y=age))+
  ggtitle("Age Boxplot")+ylab("Age")

# Consumer Price Index Distribution Graphs
summary(bank$cons.price.idx)
# Using GGplot, I constructed a bar graph to show the distribution of the consumer price index
bar_price.idx=ggplot(bank, aes(x = cons.price.idx, fill=cons.price.idx)) + geom_bar() 

# Consumer Confidence Index Graphs 
summary(bank$cons.conf.idx)
bar_conf.idx=ggplot(bank, aes(x = cons.conf.idx, fill=cons.conf.idx)) + geom_bar() 

#Employment Variation Rates Graphs
summary(bank$emp.var.rate)
bar_emp=ggplot(bank, aes(x = emp.var.rate, fill=emp.var.rate)) + geom_bar() 
his_emp = gg + geom_histogram(aes(x=emp.var.rate), color="black", fill="white", binwidth = 1)+
  ggtitle("Distribution of Employment Variation Rate")+xlab("Employment Variation Rate")+ylab("Counts")+
  geom_vline(aes(xintercept=mean(emp.var.rate),color="red"))+
  theme(legend.position = "none")

# 3 Months Euribor Rate Graphs
summary(bank$euribor3m)
his_euribor3m = gg + geom_histogram(aes(x=euribor3m), color="black", fill="white", binwidth = 0.1)+
  ggtitle("Distribution of 3 Months Euribor Rate")+xlab("3 Months Euribor Rate")+ylab("Counts")+
  geom_vline(aes(xintercept=mean(euribor3m),color="red"))+
  theme(legend.position = "none")
bar_euribor3m=ggplot(bank, aes(x = euribor3m, fill=euribor3m)) + geom_bar() 

# Numbers of Employees Graphs
summary(bank$nr.employed)
his_employees = gg + geom_histogram(aes(x=nr.employed), color="black", fill="white", binwidth = 10)+
  ggtitle("Distribution of Numbers of Employees")+xlab("Numbers of Employees")+ylab("Counts")+
  geom_vline(aes(xintercept=mean(nr.employed),color="red"))+
  theme(legend.position = "none")

bar_employee=ggplot(bank, aes(x = nr.employed, fill=nr.employed)) + geom_bar() 

str(bank)

# Martial Status 
# bar chart for martial status
gg_martial = ggplot(bank, aes(x = marital, fill=marital)) + geom_bar() + 
  ggtitle("Distribution of Martial Status") + xlab("Martial Status")

#Job
# bar chart for job
gg_job = ggplot(bank, aes(x = job, fill=job))+geom_bar() 

#Education 
# bar chart for education
gg_edu=ggplot(bank, aes(x = education, fill=education))+geom_bar()
```




```{r, ref.label=knitr::all_labels(),echo=TRUE,eval=FALSE}
# this is the code appendix 
```